version: '3'

services:
  mysql:
    build:
      context: ./docker/mysql
      args:
        mysql_version: 5.7
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    restart: always 
    # command: --init-file /data/application/init.sql #ojo aquí Añado esto para del init
    volumes:
  #    - /opt/mysql_data:/var/lib/mysql   Este era el que utilizaba para el primer volume
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql   #Añado este para el init



  php:
    build:
      context: ./docker/php
      args:
        php_version: 7.3-apache
    container_name: docker-php
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    links:
      - mysql
